### ISSUE TITLE
default_array_item_task_type not working

### ISSUE THREAD

**Issue by pawamoy** [nat-n/poethepoet#5]
My tasks:

```toml
[tool.poe.tasks]
default_array_item_task_type = "shell"

[tool.poe.tasks.clean]
ignore_fail = true
sequence = [
    "rm -rf .coverage* 2>/dev/null",
    "rm -rf .mypy_cache 2>/dev/null",
    "rm -rf .pytest_cache 2>/dev/null",
    "rm -rf build 2>/dev/null",
    "rm -rf dist 2>/dev/null",
    "rm -rf pip-wheel-metadata 2>/dev/null",
    "rm -rf site 2>/dev/null",
    "find . -type d -name __pycache__ | xargs rm -rf 2>/dev/null",
    "find . -name '*.rej' -delete 2>/dev/null",
]
```

Running task clean:

```console
$ poetry run poe clean
Traceback (most recent call last):
  File "/path/to/venv/bin/poe", line 8, in <module>
    sys.exit(main())
  File "/path/to/venv/site-packages/poethepoet/__init__.py", line 19, in main
    result = app(cli_args=sys.argv[1:])
  File "/path/to/venv/site-packages/poethepoet/app.py", line 50, in __call__
    return self.run_task() or 0
  File "/path/to/venv/site-packages/poethepoet/app.py", line 81, in run_task
    dry=self.ui["dry_run"],
  File "/path/to/venv/site-packages/poethepoet/task/base.py", line 145, in run
    return self._handle_run(executor, list(extra_args), project_dir, env, dry)
  File "/path/to/venv/site-packages/poethepoet/task/sequence.py", line 64, in _handle_run
    extra_args=tuple(), project_dir=project_dir, env=env, dry=dry,
  File "/path/to/venv/site-packages/poethepoet/task/base.py", line 145, in run
    return self._handle_run(executor, list(extra_args), project_dir, env, dry)
  File "/path/to/venv/site-packages/poethepoet/task/ref.py", line 41, in _handle_run
    task = self.from_config(self.content, self._config, ui=self._ui)
  File "/path/to/venv/site-packages/poethepoet/task/base.py", line 86, in from_config
    raise Exception(f"Cannot instantiate unknown task {task_name!r}")
Exception: Cannot instantiate unknown task 'rm -rf .coverage* 2>/dev/null'
```

It seems poe (v0.7.0) still tries to match each item as a task reference.

**Comment by pawamoy** [comment]
Ah, my bad:

```diff
-[tool.poe.tasks]
+[tool.poe]
 default_array_item_task_type = "shell"
```
