### ISSUE TITLE
Must have tasks listed in `pyproject.toml` for `include = /path/to/tasks.toml` to work

### ISSUE THREAD

**Issue by relsunkaev** [nat-n/poethepoet#50]
### How to reproduce
With the following setup
#### **`pyproject.toml`**
```TOML
[tool.poe]
include = "./tasks.toml"
```

#### **`tasks.toml`**
```TOML
[tool.poe.tasks]
foo = { cmd = "echo bar }
```
Run
```
poe foo
```
### Output
```
Traceback (most recent call last):
  File "/Users/.../bin/poe", line 8, in <module>
    sys.exit(main())
  File "/Users/.../poethepoet/__init__.py", line 32, in main
    result = app(cli_args=sys.argv[1:])
  File "/Users/.../poethepoet/app.py", line 44, in __call__
    self.config.load(self.ui["project_root"])
  File "/Users/.../poethepoet/config.py", line 113, in load
    self._load_includes(self._project_dir)
  File "/Users/.../poethepoet/config.py", line 250, in _load_includes
    self._merge_config(tomli.load(file), include_path)
  File "/Users/.../poethepoet/config.py", line 284, in _merge_config
    own_tasks = self._poe["tasks"]
KeyError: 'tasks'
```
### Workaround
Add an empty `tasks` inline table to the config
#### **`pyproject.toml`**
```TOML
[tool.poe]
include = "./tasks.toml"
tasks = {}
```
### Environment
|Software|Version|
|-|-|
|OS| macOS 12.1|
|Python|3.9.9|
|Poetry|1.1.12|
|Poethepoet|0.12.1|

**Comment by nat-n** [comment]
Hi @relsunkaev,

Thanks for the details bug report. Looks like I missed an edge case!

We should have a fix out for this shortly.

**Comment by nat-n** [comment]
Et voilà https://github.com/nat-n/poethepoet/releases/tag/v0.12.2
